"""Phase 2 (isolated): validation + static-analysis metrics.

Reads the refactorings ALREADY generated by generate_refactorings.py under
refactored_code/<snippet>/<persona>/replica_N/code.java and, for each round:

  1. git-restores the original source in the single Defects4J checkout dir,
     runs a SonarQube baseline scan (complexity + code_smells);
  2. overwrites the source with the refactored code;
  3. defects4j compile;
  4. defects4j test  -> behavior-preservation validity gate;
  5. SonarQube post-refactoring scan (only when tests PASS);
  6. restores the source and writes one row to the ledger CSV.

It NEVER calls the LLM, so it cannot overwrite or re-generate Phase 1 output.
Resumable: rounds already present in the ledger are skipped.
"""

import os
import sys
import time
import json
import subprocess
from typing import Optional, Set

import core.pipeline_common as common
import core.defects4j_mgr
import core.sonarqube_anal
import core.ledger
# Reuse the SonarQube online-guard / retry helpers (no duplication).
from main import ensure_sonarqube_online, call_sonar_with_retry

# Path prefix the snippet metadata carries; stripped to get the repo-relative path.
FINDER_PREFIX = "temp_workspace/finder_Math_1/"


def _git_restore(checkout_dir: str, rel_path: str) -> None:
    """Discard local edits to a single tracked file in the checkout."""
    subprocess.run(
        ["git", "-C", checkout_dir, "checkout", "--", rel_path],
        capture_output=True,
        stdin=subprocess.DEVNULL,
    )


def _load_baseline_cache(path: str) -> dict:
    """Baseline metrics are persona/replica-independent (original source), so we
    scan each snippet's baseline once and cache it. Persisted for resumability."""
    if os.path.exists(path):
        try:
            with open(path, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception:
            pass
    return {}


def _save_baseline_cache(path: str, cache: dict) -> None:
    with open(path, "w", encoding="utf-8") as f:
        json.dump(cache, f, indent=2)


def _build_sonar_mgr(settings: dict) -> core.sonarqube_anal.SonarQubeManager:
    sonar_path = settings["sonar_scanner_path"]
    if os.path.exists(sonar_path):
        sonar_path = os.path.abspath(sonar_path)
    return core.sonarqube_anal.SonarQubeManager(
        url=settings["sonar_url"], token=settings["sonar_token"], scanner_bin=sonar_path,
    )


def precompute_baselines(
    settings_path: str = "config/settings.json",
    snippets_path: str = "candidates_subset.json",
    baseline_cache_path: str = "baseline_cache.json",
    checkout_dir_override: Optional[str] = None,
) -> dict:
    """Scan the original source of every UNIQUE snippet once and persist the
    baseline (complexity, code_smells). Run serially before forking parallel
    workers so they never race to scan/write the same baseline."""
    logger = common.get_logger()
    settings, snippets = common.load_config(settings_path, snippets_path)
    checkout_dir = checkout_dir_override or common.get_checkout_dir(settings)
    classes_dir_abs = os.path.abspath(os.path.join(checkout_dir, "target", "classes"))
    sonar_mgr = _build_sonar_mgr(settings)
    cache = _load_baseline_cache(baseline_cache_path)

    seen = set()
    for snippet in snippets:
        sid = snippet["trecho"]
        if sid in seen or sid in cache:
            seen.add(sid)
            continue
        seen.add(sid)
        rel_path = snippet["file_path"].replace(FINDER_PREFIX, "")
        abs_source_file = os.path.join(checkout_dir, rel_path)
        _git_restore(checkout_dir, rel_path)
        key = f"{sid}_baseline"
        logger.info(f"Baseline scan {len(cache) + 1} for {sid}.")
        call_sonar_with_retry(sonar_mgr, sonar_mgr.scan, key, key, abs_source_file, classes_dir_abs)
        if not call_sonar_with_retry(sonar_mgr, sonar_mgr.wait_for_task, key):
            raise core.sonarqube_anal.SonarQubeError(f"Baseline task failed for {sid}.")
        m = call_sonar_with_retry(sonar_mgr, sonar_mgr.get_metrics, key)
        call_sonar_with_retry(sonar_mgr, sonar_mgr.delete_project, key)
        cache[sid] = {"complexity": m.get("complexity", 0), "code_smells": m.get("code_smells", 0)}
        _save_baseline_cache(baseline_cache_path, cache)
    logger.info(f"Precomputed {len(cache)} baselines into '{baseline_cache_path}'.")
    return cache


def run_validation(
    settings_path: str = "config/settings.json",
    snippets_path: str = "candidates_subset.json",
    ledger_path: str = "checkpoint_ledger_phase2.csv",
    personas_override: Optional[dict] = None,
    replicas_override: Optional[int] = None,
    max_rounds: Optional[int] = None,
    baseline_cache_path: str = "baseline_cache.json",
    checkout_dir_override: Optional[str] = None,
    only_round_ids: Optional[Set[int]] = None,
    freeze_baseline: bool = False,
    worker_tag: str = "",
) -> None:
    logger = common.get_logger()
    tag = f"[{worker_tag}] " if worker_tag else ""
    logger.info(f"{tag}Starting Phase 2: Validation & Metrics (isolated).")

    settings, snippets = common.load_config(settings_path, snippets_path)
    personas = common.resolve_personas(personas_override)
    replicas = common.resolve_replicas(replicas_override)
    rounds_metadata = common.build_rounds(snippets, personas, replicas)
    total_rounds = len(rounds_metadata)

    checkout_dir = checkout_dir_override or common.get_checkout_dir(settings)
    if not os.path.isdir(checkout_dir):
        logger.error(f"Checkout dir not found: {checkout_dir}. Restore the Defects4J Math-1 checkout first.")
        sys.exit(1)

    # Managers: abspath the wrapper scripts when they exist (matches main.py).
    d4j_path = settings["defects4j_path"]
    if os.path.exists(d4j_path):
        d4j_path = os.path.abspath(d4j_path)

    sonar_mgr = _build_sonar_mgr(settings)
    d4j_mgr = core.defects4j_mgr.Defects4JManager(
        d4j_bin=d4j_path,
        java_home=settings.get("java_home"),
        perl5lib=settings.get("perl5lib"),
    )
    ledger_mgr = core.ledger.LedgerManager(filepath=ledger_path)
    completed_ids = ledger_mgr.get_completed_ids()
    logger.info(f"Loaded {len(completed_ids)} completed rounds from ledger '{ledger_path}'.")

    baseline_cache = _load_baseline_cache(baseline_cache_path)
    logger.info(f"Loaded {len(baseline_cache)} cached snippet baselines from '{baseline_cache_path}'.")

    classes_dir_abs = os.path.abspath(os.path.join(checkout_dir, "target", "classes"))

    # Per-worker scanner isolation: concurrent native scans must NOT share the
    # scanner working dir (default <cwd>/.scannerwork) nor the engine cache
    # (SONAR_USER_HOME) — both cause "Failed to delete temp folder" races.
    scan_work_dir = None
    if worker_tag:
        iso = os.path.abspath(os.path.join(settings["workspace_root"], f".scanner_{worker_tag}"))
        os.environ["SONAR_USER_HOME"] = iso + "_home"
        os.makedirs(os.environ["SONAR_USER_HOME"], exist_ok=True)
        scan_work_dir = iso + "_work"

    round_times = []
    last_failure = "Nenhuma"
    scanned_pos_projects: Set[str] = set()
    processed = 0

    for round_info in rounds_metadata:
        rid = round_info["id_rodada"]
        snippet = round_info["snippet"]
        persona_key = round_info["persona_key"]
        replica = round_info["replica"]

        if only_round_ids is not None and rid not in only_round_ids:
            continue
        if rid in completed_ids:
            continue
        if max_rounds is not None and processed >= max_rounds:
            logger.info(f"{tag}Reached max_rounds={max_rounds}; stopping.")
            break

        round_start_time = time.time()
        snippet_id = snippet["trecho"]
        logger.info(f"{tag}--- Round {rid}/{total_rounds} (Snippet: {snippet_id}, Persona: {persona_key}, Replica: {replica}) ---")

        refac_dir = os.path.join("refactored_code", snippet_id, persona_key, f"replica_{replica}")
        refac_file = os.path.join(refac_dir, "code.java")
        tokens_file = os.path.join(refac_dir, "tokens.json")

        status = "VALIDO"
        complexity_base = complexity_pos = smells_base = smells_pos = None
        token_count = prompt_tokens = candidates_tokens = 0

        # Phase 1 must have produced the refactoring for this round.
        if os.path.exists(refac_file + ".error") or not os.path.exists(refac_file):
            status = "FALHA_API"
            logger.warning(f"Skipping round {rid}: refactoring missing/errored from Phase 1.")
            ledger_mgr.write_row({
                "id_rodada": rid, "trecho": snippet_id,
                "refatoracao_tipo": snippet["refatoracao_tipo"],
                "persona": persona_key, "replica": replica, "status": status,
                "complexity_base": "", "complexity_pos": "", "complexity_delta": "",
                "smells_base": "", "smells_pos": "", "smells_delta": "",
                "tempo_execucao_seg": 0, "token_count": 0,
                "prompt_tokens": 0, "candidates_tokens": 0,
            })
            processed += 1
            continue

        # Token usage saved by generate_refactorings.py (refac_dir/tokens.json).
        try:
            with open(tokens_file, "r", encoding="utf-8") as f_tok:
                tok = json.load(f_tok)
            token_count = tok.get("total_tokens", 0)
            prompt_tokens = tok.get("prompt_tokens", 0)
            candidates_tokens = tok.get("candidates_tokens", 0)
        except Exception:
            pass

        rel_path = snippet["file_path"].replace(FINDER_PREFIX, "")
        abs_source_file = os.path.join(checkout_dir, rel_path)
        persona_tag = persona_key.replace("-", "")
        project_key_base = f"{snippet_id}_P{persona_tag}_R{replica}_base"
        project_key_pos = f"{snippet_id}_P{persona_tag}_R{replica}"

        try:
            # 1. Baseline (original source). Cached per snippet — persona/replica
            #    independent — so it is scanned only once per snippet, not per round.
            _git_restore(checkout_dir, rel_path)
            if snippet_id in baseline_cache:
                complexity_base = baseline_cache[snippet_id]["complexity"]
                smells_base = baseline_cache[snippet_id]["code_smells"]
                logger.info(f"{tag}Baseline cache hit for {snippet_id} (complexity={complexity_base}, smells={smells_base}).")
            elif freeze_baseline:
                # Parallel worker: baselines are precomputed; a miss means the
                # snippet was skipped upstream. Proceed without a baseline delta
                # rather than scan (which would race other workers on the cache).
                logger.warning(f"{tag}Baseline cache MISS for {snippet_id} with freeze_baseline; delta will be blank.")
            else:
                logger.info("SonarQube baseline scan (first time for this snippet).")
                call_sonar_with_retry(sonar_mgr, sonar_mgr.scan, project_key_base, f"{snippet_id}_base", abs_source_file, classes_dir_abs, scan_work_dir)
                if not call_sonar_with_retry(sonar_mgr, sonar_mgr.wait_for_task, project_key_base):
                    raise core.sonarqube_anal.SonarQubeError("Baseline SonarQube task failed.")
                metrics_base = call_sonar_with_retry(sonar_mgr, sonar_mgr.get_metrics, project_key_base)
                complexity_base = metrics_base.get("complexity", 0)
                smells_base = metrics_base.get("code_smells", 0)
                call_sonar_with_retry(sonar_mgr, sonar_mgr.delete_project, project_key_base)
                baseline_cache[snippet_id] = {"complexity": complexity_base, "code_smells": smells_base}
                _save_baseline_cache(baseline_cache_path, baseline_cache)

            # 2. Apply the refactored code.
            with open(refac_file, "r", encoding="utf-8") as f_ref:
                refactored_code = f_ref.read()
            with open(abs_source_file, "w", encoding="utf-8") as f_out:
                f_out.write(refactored_code)

            # 3. Compile.
            logger.info("Compiling refactored code.")
            if not d4j_mgr.compile(checkout_dir):
                status = "FALHA_COMPILACAO"
                logger.error("Compilation failed.")
            else:
                # 4. Validity gate: full test suite.
                logger.info("Running test suite.")
                test_result = d4j_mgr.test(checkout_dir, timeout=180)
                if test_result != "PASS":
                    status = test_result  # FALHA_TESTES_COMPORTAMENTO | FALHA_TESTES_TIMEOUT
                    logger.error(f"Tests failed: {test_result}")
                else:
                    # 5. Post-refactoring metrics.
                    logger.info("SonarQube post-refactoring scan.")
                    call_sonar_with_retry(sonar_mgr, sonar_mgr.scan, project_key_pos, snippet_id, abs_source_file, classes_dir_abs, scan_work_dir)
                    scanned_pos_projects.add(project_key_pos)
                    if not call_sonar_with_retry(sonar_mgr, sonar_mgr.wait_for_task, project_key_pos):
                        raise core.sonarqube_anal.SonarQubeError("Post-refactoring SonarQube task failed.")
                    metrics_pos = call_sonar_with_retry(sonar_mgr, sonar_mgr.get_metrics, project_key_pos)
                    complexity_pos = metrics_pos.get("complexity", 0)
                    smells_pos = metrics_pos.get("code_smells", 0)
                    status = "VALIDO"
                    logger.info("Round VALIDO.")

        except core.sonarqube_anal.SonarQubeError as e:
            status = "FALHA_ANALISE"
            logger.error(f"SonarQube analysis error: {e}")
        except Exception as e:
            status = "ERRO_SISTEMA"
            logger.error(f"Unexpected system error: {e}")
        finally:
            # 6. Always restore the source so the next round starts clean.
            _git_restore(checkout_dir, rel_path)

            complexity_delta = (complexity_pos - complexity_base) if (complexity_base is not None and complexity_pos is not None) else ""
            smells_delta = (smells_pos - smells_base) if (smells_base is not None and smells_pos is not None) else ""
            tempo = time.time() - round_start_time

            ledger_mgr.write_row({
                "id_rodada": rid, "trecho": snippet_id,
                "refatoracao_tipo": snippet["refatoracao_tipo"],
                "persona": persona_key, "replica": replica, "status": status,
                "complexity_base": complexity_base if complexity_base is not None else "",
                "complexity_pos": complexity_pos if complexity_pos is not None else "",
                "complexity_delta": complexity_delta,
                "smells_base": smells_base if smells_base is not None else "",
                "smells_pos": smells_pos if smells_pos is not None else "",
                "smells_delta": smells_delta,
                "tempo_execucao_seg": round(tempo, 2),
                "token_count": token_count,
                "prompt_tokens": prompt_tokens,
                "candidates_tokens": candidates_tokens,
            })

            round_times.append(tempo)
            if status != "VALIDO":
                last_failure = f"Rodada {rid} ({status})"
            avg = sum(round_times) / len(round_times)
            logger.info(f"{tag}PROGRESSO rodada {rid} | Status: {status} | {tempo:.1f}s | feitas={processed + 1} | média={avg:.1f}s | última falha: {last_failure}")

            processed += 1

            # Periodically free SonarQube DB space.
            if rid % 30 == 0 and scanned_pos_projects:
                logger.info(f"Cleaning up {len(scanned_pos_projects)} SonarQube projects.")
                for key in list(scanned_pos_projects):
                    call_sonar_with_retry(sonar_mgr, sonar_mgr.delete_project, key)
                scanned_pos_projects.clear()

    logger.info("Phase 2 finished.")


if __name__ == "__main__":
    settings_arg = sys.argv[1] if len(sys.argv) > 1 else "config/settings.json"
    snippets_arg = sys.argv[2] if len(sys.argv) > 2 else "candidates_subset.json"
    ledger_arg = sys.argv[3] if len(sys.argv) > 3 else "checkpoint_ledger_phase2.csv"
    max_arg = int(sys.argv[4]) if len(sys.argv) > 4 else None
    run_validation(settings_path=settings_arg, snippets_path=snippets_arg, ledger_path=ledger_arg, max_rounds=max_arg)
